[project]
channels = ["conda-forge", "r", "bioconda", "currocamp"]
name = "what-are-genomic-offsets-paper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
black = "black analysis/**/*.py"
snakefmt = "snakefmt analysis/**/Snakefile"
lint = { depends-on = ["black", "snakefmt"] }


[dependencies]
tskit = ">=0.6.0,<0.7"
msprime = ">=1.3.3,<2"
pandas = ">=2.2.3,<3"
pyslim = ">=1.0.4,<2"
slim = ">=4.3,<5"
snakemake = ">=8.29.0,<9"
r-tidyverse = ">=2.0.0,<3"
jupyterlab = ">=4.3.5,<5"
genomic_offsets = ">=0.1.2,<0.2"
numpy = "==2.1.3"
matplotlib = ">=3.10.1,<4"
snakefmt = ">=0.10.2,<0.11"
black = ">=24.10.0,<25"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
