[project]
channels = ["conda-forge", "r", "bioconda", "currocamp"]
name = "what-are-genomic-offsets-paper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lint = "black analysis/**/*.py"

[dependencies]
tskit = ">=0.6.0,<0.7"
msprime = ">=1.3.3,<2"
pandas = ">=2.2.3,<3"
pyslim = ">=1.0.4,<2"
slim = ">=4.3,<5"
snakemake = ">=8.29.0,<9"
r-tidyverse = ">=2.0.0,<3"
jupyterlab = ">=4.3.5,<5"
black = ">=25.1.0,<26"
genomic_offsets = ">=0.1.2,<0.2"
numpy = "==2.1.3"
matplotlib = ">=3.10.1,<4"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
